FROM kakadadroid/python-talib:3.3
MAINTAINER skeang@gmail.com

# Instructions from https://github.com/jupyterhub/jupyterhub
RUN apt-get install -y npm nodejs-legacy
RUN npm install -g configurable-http-proxy
RUN pip3 install jupyterhub

CMD jupyterhub --no-ssl

