test:
  build: .
  dockerfile: Dockerfile.test
  volumes:
    - ./:/usr/src/app

live:
  build: .
  dockerfile: Dockerfile.live
  ports:
    - "8333:8000"
  volumes:
    - ./home:/home
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log

