live:
  build: .
  env_file: .env
  ports:
    - "8333:8000"
  volumes:
    - ./home:/home
    - ./srv/oauthenticator:/srv/oauthenticator
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log
    - ./:/usr/src/app/
    - ./zipline_root:/home/.zipline

test:
  build: .
  env_file: .env.sample
  volumes:
    - ./home:/home
    - ./srv/oauthenticator:/srv/oauthenticator
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log
    - ./:/usr/src/app/
    - ./zipline_root:/home/.zipline
  command: py.test

