hub:
  build: .
  env_file: .env
  ports:
    - "8333:8000"
  volumes:
    - ./home:/home
    - ./srv/oauthenticator:/srv/oauthenticator
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log
    - ./:/usr/src/app/
    - ./zipline_root:/home/.zipline
    - ./home/jupyter/images:/usr/local/share/jupyter/hub/static/images

# Somehow pandas==0.18.1 doesn't play nice with zipline.
# We build a new image with 0.18.1 for ingesting data, because
# it's way faster than 0.17.1
ingest:
  build: .
  env_file: .env.sample
  dockerfile: ingest.Dockerfile
  volumes:
    - ./home:/home
    - ./srv/oauthenticator:/srv/oauthenticator
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log
    - ./:/usr/src/app/
    - ./zipline_root:/home/.zipline
  command: python ingest.py

test:
  build: .
  env_file: .env.sample
  volumes:
    - ./home:/home
    - ./srv/oauthenticator:/srv/oauthenticator
    - ./srv/jupyterhub:/srv/jupyterhub
    - ./etc/jupyterhub:/etc/jupyterhub
    - ./var/log:/var/log
    - ./:/usr/src/app/
    - ./zipline_root:/home/.zipline
  command: py.test

